<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class QuestionsBankSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $questions = [
            [
                'question_name' => 'Which of the following is a quadratic expression in one variable?',
                'academic_level' => 'Form 4',
                'chapter' => 'Quadratic Functions',
                'subject' => 'Mathematics',
                'difficulty' => 'Easy',
                'question_image' => null,
                'answer_image' => null,
                'option_a' => '2x + 2y',
                'option_b' => '3y²',
                'option_c' => 'x² + y + 5',
                'option_d' => 'x/2 + 4',
                'answer' => 'B',
                'tip_easy' => 'A quadratic expression in one variable contains only one variable raised to the power of 2.',
                'tip_intermediate' => 'Look for expressions with a single variable where the highest power is 2.',
                'tip_advanced' => 'Remember that quadratic expressions in one variable have the form ax² + bx + c where a ≠ 0.',
                'uploaded_by' => 'Teacher A',
                'upload_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_name' => 'Solve for x: x² - 5x + 6 = 0',
                'academic_level' => 'Form 4',
                'chapter' => 'Quadratic Equations',
                'subject' => 'Mathematics',
                'difficulty' => 'Intermediate',
                'question_image' => null,
                'answer_image' => null,
                'option_a' => 'x = 2, 3',
                'option_b' => 'x = 1, 6',
                'option_c' => 'x = -2, -3',
                'option_d' => 'x = 0, 5',
                'answer' => 'A',
                'tip_easy' => 'Try factoring the quadratic equation first.',
                'tip_intermediate' => 'Factor as (x-2)(x-3) = 0, so x = 2 or x = 3.',
                'tip_advanced' => 'Use factoring or the quadratic formula: x = (5 ± √(25-24))/2 = (5 ± 1)/2.',
                'uploaded_by' => 'Teacher B',
                'upload_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_name' => 'What is the vertex of y = x² - 4x + 3?',
                'academic_level' => 'Form 4',
                'chapter' => 'Quadratic Functions',
                'subject' => 'Mathematics',
                'difficulty' => 'Advanced',
                'question_image' => null,
                'answer_image' => null,
                'option_a' => '(2, -1)',
                'option_b' => '(2, 1)',
                'option_c' => '(-2, -1)',
                'option_d' => '(-2, 1)',
                'answer' => 'A',
                'tip_easy' => 'The vertex is the turning point of the parabola.',
                'tip_intermediate' => 'Complete the square or use the formula x = -b/2a to find the x-coordinate.',
                'tip_advanced' => 'x = -(-4)/(2×1) = 2, then y = (2)² - 4(2) + 3 = 4 - 8 + 3 = -1.',
                'uploaded_by' => 'Teacher C',
                'upload_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_name' => 'What is the probability of getting heads when flipping a fair coin?',
                'academic_level' => 'Form 5',
                'chapter' => 'Mathematical Modelling',
                'subject' => 'Mathematics',
                'difficulty' => 'Easy',
                'question_image' => null,
                'answer_image' => null,
                'option_a' => '0',
                'option_b' => '1/2',
                'option_c' => '1',
                'option_d' => '2',
                'answer' => 'B',
                'tip_easy' => 'A fair coin has two equally likely outcomes.',
                'tip_intermediate' => 'Probability = favorable outcomes / total outcomes = 1/2.',
                'tip_advanced' => 'For a fair coin, P(heads) = P(tails) = 0.5 = 1/2.',
                'uploaded_by' => 'Teacher D',
                'upload_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_name' => 'What is the area of a circle with radius 5cm?',
                'academic_level' => 'Form 5',
                'chapter' => 'Congruency, Enlargement and Combined Transformations',
                'subject' => 'Mathematics',
                'difficulty' => 'Intermediate',
                'question_image' => null,
                'answer_image' => null,
                'option_a' => '10π cm²',
                'option_b' => '5π cm²',
                'option_c' => '25π cm²',
                'option_d' => '50π cm²',
                'answer' => 'C',
                'tip_easy' => 'Use the formula for the area of a circle.',
                'tip_intermediate' => 'Area = πr² where r is the radius.',
                'tip_advanced' => 'Area = π × (5)² = π × 25 = 25π cm².',
                'uploaded_by' => 'Teacher E',
                'upload_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_name' => 'Factor: x² + 7x + 12',
                'academic_level' => 'Form 4',
                'chapter' => 'Quadratic Functions',
                'subject' => 'Mathematics',
                'difficulty' => 'Easy',
                'question_image' => null,
                'answer_image' => null,
                'option_a' => '(x+3)(x+4)',
                'option_b' => '(x+2)(x+6)',
                'option_c' => '(x+1)(x+12)',
                'option_d' => '(x-3)(x-4)',
                'answer' => 'A',
                'tip_easy' => 'Look for two numbers that multiply to 12 and add to 7.',
                'tip_intermediate' => 'Find factors of 12: 1×12, 2×6, 3×4. Which pair adds to 7?',
                'tip_advanced' => '3 + 4 = 7 and 3 × 4 = 12, so (x+3)(x+4).',
                'uploaded_by' => 'Teacher A',
                'upload_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_name' => 'Complete the square: x² + 6x + 5',
                'academic_level' => 'Form 4',
                'chapter' => 'Quadratic Functions',
                'subject' => 'Mathematics',
                'difficulty' => 'Intermediate',
                'question_image' => null,
                'answer_image' => null,
                'option_a' => '(x+3)² - 4',
                'option_b' => '(x+3)² + 4',
                'option_c' => '(x+6)² - 5',
                'option_d' => '(x+6)² + 5',
                'answer' => 'A',
                'tip_easy' => 'Take half of the coefficient of x and square it.',
                'tip_intermediate' => 'Half of 6 is 3, so we get (x+3)². Then adjust the constant.',
                'tip_advanced' => 'x² + 6x + 5 = (x+3)² - 9 + 5 = (x+3)² - 4.',
                'uploaded_by' => 'Teacher B',
                'upload_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_name' => 'What is the mean of the numbers: 2, 4, 6, 8, 10?',
                'academic_level' => 'Form 5',
                'chapter' => 'Measures of Dispersion of Grouped Data',
                'subject' => 'Mathematics',
                'difficulty' => 'Easy',
                'question_image' => null,
                'answer_image' => null,
                'option_a' => '5',
                'option_b' => '5.5',
                'option_c' => '6',
                'option_d' => '7',
                'answer' => 'C',
                'tip_easy' => 'Add all numbers and divide by how many numbers there are.',
                'tip_intermediate' => 'Mean = sum of all values / number of values.',
                'tip_advanced' => 'Mean = (2+4+6+8+10)/5 = 30/5 = 6.',
                'uploaded_by' => 'Teacher C',
                'upload_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_name' => 'If f(x) = 2x + 3, what is f(5)?',
                'academic_level' => 'Form 4',
                'chapter' => 'Functions',
                'subject' => 'Mathematics',
                'difficulty' => 'Easy',
                'question_image' => null,
                'answer_image' => null,
                'option_a' => '10',
                'option_b' => '11',
                'option_c' => '13',
                'option_d' => '15',
                'answer' => 'C',
                'tip_easy' => 'Replace x with 5 in the function.',
                'tip_intermediate' => 'Substitute x = 5 into f(x) = 2x + 3.',
                'tip_advanced' => 'f(5) = 2(5) + 3 = 10 + 3 = 13.',
                'uploaded_by' => 'Teacher D',
                'upload_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_name' => 'What is the value of log₂ 8?',
                'academic_level' => 'Form 4',
                'chapter' => 'Number Bases',
                'subject' => 'Mathematics',
                'difficulty' => 'Intermediate',
                'question_image' => null,
                'answer_image' => null,
                'option_a' => '2',
                'option_b' => '3',
                'option_c' => '4',
                'option_d' => '8',
                'answer' => 'B',
                'tip_easy' => 'Think: what power of 2 gives 8?',
                'tip_intermediate' => 'log₂ 8 means: 2 to what power equals 8?',
                'tip_advanced' => '2³ = 8, so log₂ 8 = 3.',
                'uploaded_by' => 'Teacher E',
                'upload_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ];

        // Clean existing records to avoid duplicates on reseed
        DB::table('questions')->truncate();

        // Insert all questions using batch insert for better performance
        DB::table('questions')->insert($questions);

        $this->command->info('Successfully seeded ' . count($questions) . ' questions!');
    }
}
